# Generated by Django 4.2 on 2023-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('about_image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Planing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('property1', models.CharField(max_length=250)),
                ('property2', models.CharField(max_length=250)),
                ('property3', models.CharField(max_length=250)),
                ('property4', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Services', max_length=50)),
                ('title1', models.CharField(max_length=50)),
                ('content1', models.TextField()),
                ('title2', models.CharField(max_length=50)),
                ('content2', models.TextField()),
                ('title3', models.CharField(max_length=50)),
                ('content3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.TextField(max_length=250)),
                ('image_name', models.CharField(max_length=30)),
                ('category', models.ManyToManyField(to='home.gallerytype')),
            ],
        ),
    ]
