# Generated by Django 4.2 on 2023-04-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('about_image', models.ImageField(upload_to='static/img/about_images/')),
            ],
        ),
    ]
