# Generated by Django 4.2 on 2023-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(to='home.gallerytype'),
        ),
    ]
