# Generated by Django 4.2 on 2023-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.TextField(max_length=250),
        ),
    ]
