# Generated by Django 4.2 on 2023-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeri_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.TextField(max_length=250)),
                ('imagename', models.CharField(max_length=30)),
                ('category', models.ManyToManyField(to='home.galeri_name')),
            ],
        ),
    ]
