# Generated by Django 4.2 on 2023-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='galeri',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='galeri_name',
            new_name='GalleryType',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='imagename',
            new_name='image_name',
        ),
    ]
